FROM openjdk:8-jdk-alpine
COPY target/ManagerAssigment-Nashtech-0.0.1-SNAPSHOT.jar ManagerAssigment-Nashtech-0.0.1-SNAPSHOT.jar 
ENTRYPOINT [ "java","-jar,"/ManagerAssigment-Nashtech-0.0.1-SNAPSHOT.jar"] 